dist: trusty
sudo: required
before_install:
  - wget -O /tmp/perl6.deb https://github.com/nxadm/rakudo-pkg/releases/download/v2018.03/rakudo-pkg-Ubuntu14.04_2018.03-01_amd64.deb  && sudo dpkg -i /tmp/perl6.deb && export PATH=$PATH:/.perl6/bin:/opt/rakudo-pkg/bin && install-zef-as-user  && zef install .
script:
  - zef test .
